# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_1', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', max_length=3)),
                ('nivel_2', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', max_length=3)),
                ('nivel_3', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], default='OFF', max_length=3)),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
