# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0003_auto_20180110_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='modbus_id',
            field=models.IntegerField(default=0),
        ),
    ]
