# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-15 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0006_auto_20180110_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('addr', models.CharField(max_length=25)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('plan', models.FileField(upload_to='uploads/buildings/')),
            ],
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('addr', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=25)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('fan', models.CharField(choices=[('Off', 'Off'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Off', max_length=3)),
                ('valve', models.BooleanField(default=False)),
                ('current', models.FloatField(default=0)),
                ('target_temp', models.FloatField(default=21.0)),
                ('target_hum', models.FloatField(default=50.0)),
                ('temperature1', models.FloatField(default=0)),
                ('temperature2', models.FloatField(default=0)),
                ('temperature3', models.FloatField(default=0)),
                ('humidity1', models.FloatField(default=0)),
                ('input1', models.BooleanField(default=False)),
                ('input2', models.BooleanField(default=False)),
                ('powermode', models.CharField(choices=[('On', 'On'), ('Off', 'Off'), ('Schedule', 'Schedule')], default='Schedule', max_length=3)),
                ('controlmode', models.CharField(choices=[('Manual', 'Manual'), ('Autom', 'Autom')], default='Autom', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(default=1)),
                ('plan', models.FileField(upload_to='uploads/plans/')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.Administrator')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('begin', models.TimeField(auto_now=True)),
                ('end', models.TimeField(auto_now=True)),
                ('cooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.Cooler')),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='cooler',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.Floor'),
        ),
    ]
