# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0009_auto_20180516_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField()),
                ('a_time', models.TimeField()),
                ('message', models.CharField(default='Revisar Conexi\xf3n de Motor', max_length=50)),
                ('send', models.BooleanField(default=False)),
                ('cooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motors.Cooler')),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='begin',
            field=models.TimeField(default='07:00:00'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.TimeField(default='15:00:00'),
        ),
    ]
