# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motors', '0010_auto_20180516_0156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alerts',
            new_name='Alert',
        ),
    ]
